import tkinter as tk
from tkinter import ttk, filedialog, messagebox, scrolledtext
import threading
import os
import time

import numpy as np
from stl import mesh

try:
    import matplotlib
    matplotlib.use("TkAgg")
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection
    HAS_MPL = True
except ImportError:
    HAS_MPL = False


C = {
    "bg":        "#0f1117",
    "panel":     "#161b22",
    "border":    "#21262d",
    "accent":    "#58a6ff",
    "accent2":   "#3fb950",
    "warn":      "#d29922",
    "error":     "#f85149",
    "text":      "#e6edf3",
    "text_dim":  "#8b949e",
    "entry_bg":  "#0d1117",
    "btn":       "#21262d",
    "btn_hover": "#30363d",
    "progress":  "#238636",
}

FONT_MONO  = ("Consolas", 10)
FONT_LABEL = ("Segoe UI", 9)
FONT_HEAD  = ("Segoe UI Semibold", 10)
FONT_TITLE = ("Segoe UI Semibold", 13)


def load_stl(path: str):
    m = mesh.Mesh.from_file(path)
    verts = m.vectors.reshape(-1, 3)
    unique_verts, inverse = np.unique(verts, axis=0, return_inverse=True)
    faces = inverse.reshape(-1, 3)
    bounds = {
        "x": (float(unique_verts[:, 0].min()), float(unique_verts[:, 0].max())),
        "y": (float(unique_verts[:, 1].min()), float(unique_verts[:, 1].max())),
        "z": (float(unique_verts[:, 2].min()), float(unique_verts[:, 2].max())),
    }
    size = {k: v[1] - v[0] for k, v in bounds.items()}
    stats = {
        "triangles":    len(m.vectors),
        "unique_verts": len(unique_verts),
        "faces":        len(faces),
        "bounds":       bounds,
        "size":         size,
        "file_size_kb": os.path.getsize(path) / 1024,
    }
    return m, unique_verts, faces, stats


def convert_to_scad(
    unique_verts, faces, stats,
    module_name:  str   = "shape",
    precision:    int   = 4,
    convexity:    int   = 10,
    scale_factor: float = 1.0,
    center:       bool  = False,
    add_call:     bool  = True,
    add_header:   bool  = True,
    winding_flip: bool  = False,
    progress_cb=None,
) -> str:
    lines = []

    if add_header:
        lines += [
            "// Generated by STL to SCAD Converter",
            f"// Triangles : {stats['triangles']}",
            f"// Vertices  : {stats['unique_verts']}",
            f"// Size X    : {stats['size']['x']:.4f}",
            f"// Size Y    : {stats['size']['y']:.4f}",
            f"// Size Z    : {stats['size']['z']:.4f}",
            "",
        ]

    verts = unique_verts.copy()

    if center:
        cx = (stats["bounds"]["x"][0] + stats["bounds"]["x"][1]) / 2
        cy = (stats["bounds"]["y"][0] + stats["bounds"]["y"][1]) / 2
        cz = (stats["bounds"]["z"][0] + stats["bounds"]["z"][1]) / 2
        verts[:, 0] -= cx
        verts[:, 1] -= cy
        verts[:, 2] -= cz

    if scale_factor != 1.0:
        verts = verts * scale_factor

    fmt = f"{{:.{precision}f}}"

    lines.append(f"module {module_name}() {{")
    lines.append("    polyhedron(")
    lines.append("        points = [")

    n_verts = len(verts)
    for i, v in enumerate(verts):
        x = fmt.format(v[0])
        y = fmt.format(v[1])
        z = fmt.format(v[2])
        lines.append(f"            [{x}, {y}, {z}],")
        if progress_cb and i % 5000 == 0:
            progress_cb(i / (n_verts + len(faces)) * 50)

    lines.append("        ],")
    lines.append("        faces = [")

    n_faces = len(faces)
    for i, f in enumerate(faces):
        if winding_flip:
            lines.append(f"            [{f[2]}, {f[1]}, {f[0]}],")
        else:
            lines.append(f"            [{f[0]}, {f[1]}, {f[2]}],")
        if progress_cb and i % 5000 == 0:
            progress_cb(50 + i / n_faces * 48)

    lines.append("        ],")
    lines.append(f"        convexity = {convexity}")
    lines.append("    );")
    lines.append("}")

    if add_call:
        lines += ["", f"{module_name}();"]

    if progress_cb:
        progress_cb(100)

    return "\n".join(lines)


def dark_style(root):
    style = ttk.Style(root)
    style.theme_use("clam")
    style.configure(".",
        background=C["panel"], foreground=C["text"],
        fieldbackground=C["entry_bg"], bordercolor=C["border"],
        darkcolor=C["border"], lightcolor=C["border"],
        troughcolor=C["bg"], selectbackground=C["accent"],
        selectforeground=C["bg"], font=FONT_LABEL,
    )
    style.configure("TFrame",       background=C["panel"])
    style.configure("TLabel",       background=C["panel"], foreground=C["text"])
    style.configure("TEntry",       fieldbackground=C["entry_bg"], foreground=C["text"],
                    insertcolor=C["text"])
    style.configure("TCheckbutton", background=C["panel"], foreground=C["text"])
    style.configure("TSpinbox",     fieldbackground=C["entry_bg"], foreground=C["text"],
                    arrowcolor=C["accent"])
    style.configure("Horizontal.TProgressbar",
                    troughcolor=C["bg"], background=C["progress"],
                    bordercolor=C["border"], lightcolor=C["progress"],
                    darkcolor=C["progress"])
    style.configure("TNotebook",    background=C["bg"], bordercolor=C["border"])
    style.configure("TNotebook.Tab",
                    background=C["btn"], foreground=C["text_dim"],
                    padding=(12, 6), font=FONT_LABEL)
    style.map("TNotebook.Tab",
              background=[("selected", C["panel"])],
              foreground=[("selected", C["accent"])])
    style.configure("Vertical.TScrollbar",
                    troughcolor=C["bg"], background=C["btn"],
                    arrowcolor=C["text_dim"])


def make_label(parent, text, dim=False, head=False, **kw):
    font  = FONT_HEAD if head else FONT_LABEL
    color = C["text_dim"] if dim else C["text"]
    return tk.Label(parent, text=text, bg=C["panel"], fg=color, font=font, **kw)


def make_entry(parent, textvariable=None, width=40, **kw):
    return tk.Entry(parent, textvariable=textvariable, width=width,
                    bg=C["entry_bg"], fg=C["text"],
                    insertbackground=C["text"],
                    relief="flat", bd=1,
                    highlightthickness=1,
                    highlightbackground=C["border"],
                    highlightcolor=C["accent"],
                    font=FONT_MONO, **kw)


def make_button(parent, text, command, accent=False, danger=False, width=None, **kw):
    bg = C["accent"] if accent else (C["error"] if danger else C["btn"])
    fg = C["bg"] if accent else C["text"]
    b = tk.Button(parent, text=text, command=command,
                  bg=bg, fg=fg,
                  activebackground=C["btn_hover"],
                  activeforeground=C["text"],
                  relief="flat", bd=0,
                  padx=14, pady=6,
                  font=FONT_HEAD,
                  cursor="hand2",
                  **({"width": width} if width else {}),
                  **kw)
    def on_enter(e): b.config(bg=C["btn_hover"] if not accent else "#79baff")
    def on_leave(e): b.config(bg=bg)
    b.bind("<Enter>", on_enter)
    b.bind("<Leave>", on_leave)
    return b


def separator(parent, **kw):
    return tk.Frame(parent, bg=C["border"], height=1, **kw)


class ScadifyApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("Scadify")
        self.geometry("1100x780")
        self.minsize(860, 640)
        self.configure(bg=C["bg"])
        dark_style(self)

        self.input_path  = tk.StringVar()
        self.output_path = tk.StringVar()
        self.module_name = tk.StringVar(value="shape")
        self.precision   = tk.IntVar(value=4)
        self.convexity   = tk.IntVar(value=10)
        self.scale_str   = tk.StringVar(value="1.0")
        self.center      = tk.BooleanVar(value=False)
        self.add_call    = tk.BooleanVar(value=True)
        self.add_header  = tk.BooleanVar(value=True)
        self.winding     = tk.BooleanVar(value=False)

        self._mesh_obj           = None
        self._unique_verts       = None
        self._faces              = None
        self._stats              = None
        self._preview_angle      = [30, -45]
        self._drag_start         = None
        self._preview_mesh_style = "solid"
        self._notebook           = None
        self._last_drag_draw     = 0

        self._build_ui()

    def _build_ui(self):
        title_bar = tk.Frame(self, bg=C["bg"], pady=8)
        title_bar.pack(fill="x", padx=16)
        tk.Label(title_bar, text="Scadify",
                 bg=C["bg"], fg=C["accent"], font=FONT_TITLE).pack(side="left")
        tk.Label(title_bar, text="  Mesh Converter & Preview",
                 bg=C["bg"], fg=C["text_dim"], font=FONT_LABEL).pack(side="left")

        separator(self).pack(fill="x")

        main = tk.Frame(self, bg=C["bg"])
        main.pack(fill="both", expand=True)

        left = tk.Frame(main, bg=C["panel"], width=360)
        left.pack(side="left", fill="y")
        left.pack_propagate(False)

        right = tk.Frame(main, bg=C["bg"])
        right.pack(side="left", fill="both", expand=True)

        self._build_left(left)
        self._build_right(right)

        separator(self).pack(fill="x")
        self._build_statusbar()

    def _build_left(self, parent):
        pad = {"padx": 16, "pady": 4}

        tk.Label(parent, text="FILES", bg=C["panel"],
                 fg=C["text_dim"], font=("Segoe UI Semibold", 8)).pack(
                     anchor="w", padx=16, pady=(14, 2))
        separator(parent).pack(fill="x", padx=16)

        f_in = tk.Frame(parent, bg=C["panel"])
        f_in.pack(fill="x", **pad)
        make_label(f_in, "STL Input", head=True).pack(anchor="w")
        row = tk.Frame(f_in, bg=C["panel"])
        row.pack(fill="x", pady=(2, 0))
        self._entry_in = make_entry(row, textvariable=self.input_path, width=28)
        self._entry_in.pack(side="left", fill="x", expand=True)
        make_button(row, "Browse", self._browse_input).pack(side="left", padx=(6, 0))

        f_out = tk.Frame(parent, bg=C["panel"])
        f_out.pack(fill="x", **pad)
        make_label(f_out, "SCAD Output", head=True).pack(anchor="w")
        row2 = tk.Frame(f_out, bg=C["panel"])
        row2.pack(fill="x", pady=(2, 0))
        self._entry_out = make_entry(row2, textvariable=self.output_path, width=28)
        self._entry_out.pack(side="left", fill="x", expand=True)
        make_button(row2, "Browse", self._browse_output).pack(side="left", padx=(6, 0))

        separator(parent).pack(fill="x", padx=16, pady=(10, 0))

        tk.Label(parent, text="MODULE", bg=C["panel"],
                 fg=C["text_dim"], font=("Segoe UI Semibold", 8)).pack(
                     anchor="w", padx=16, pady=(10, 2))
        separator(parent).pack(fill="x", padx=16)

        f_mod = tk.Frame(parent, bg=C["panel"])
        f_mod.pack(fill="x", **pad)
        make_label(f_mod, "Module Name").grid(row=0, column=0, sticky="w")
        make_entry(f_mod, textvariable=self.module_name, width=20).grid(
            row=0, column=1, sticky="ew", padx=(8, 0))
        f_mod.columnconfigure(1, weight=1)

        f_sc = tk.Frame(parent, bg=C["panel"])
        f_sc.pack(fill="x", **pad)
        make_label(f_sc, "Scale Factor").grid(row=0, column=0, sticky="w")
        make_entry(f_sc, textvariable=self.scale_str, width=12).grid(
            row=0, column=1, sticky="w", padx=(8, 0))

        f_pr = tk.Frame(parent, bg=C["panel"])
        f_pr.pack(fill="x", **pad)
        make_label(f_pr, "Decimal Precision").grid(row=0, column=0, sticky="w")
        ttk.Spinbox(f_pr, from_=1, to=10, textvariable=self.precision, width=6).grid(
            row=0, column=1, sticky="w", padx=(8, 0))

        f_cv = tk.Frame(parent, bg=C["panel"])
        f_cv.pack(fill="x", **pad)
        make_label(f_cv, "Convexity").grid(row=0, column=0, sticky="w")
        ttk.Spinbox(f_cv, from_=1, to=100, textvariable=self.convexity, width=6).grid(
            row=0, column=1, sticky="w", padx=(8, 0))
        make_label(f_cv, "  (preview hint)", dim=True).grid(row=0, column=2, sticky="w")

        separator(parent).pack(fill="x", padx=16, pady=(10, 0))

        tk.Label(parent, text="OPTIONS", bg=C["panel"],
                 fg=C["text_dim"], font=("Segoe UI Semibold", 8)).pack(
                     anchor="w", padx=16, pady=(10, 2))
        separator(parent).pack(fill="x", padx=16)

        opts = tk.Frame(parent, bg=C["panel"])
        opts.pack(fill="x", padx=16, pady=4)

        def ck(text, var, tooltip=""):
            f = tk.Frame(opts, bg=C["panel"])
            f.pack(anchor="w", pady=2)
            tk.Checkbutton(f, text=text, variable=var,
                           bg=C["panel"], fg=C["text"],
                           selectcolor=C["entry_bg"],
                           activebackground=C["panel"],
                           activeforeground=C["accent"],
                           font=FONT_LABEL, cursor="hand2").pack(side="left")
            if tooltip:
                make_label(f, f"  {tooltip}", dim=True).pack(side="left")

        ck("Center mesh at origin",   self.center,     "")
        ck("Add module call at end",  self.add_call,   "")
        ck("Flip face winding order", self.winding,    "(fix inverted normals)")
        ck("Include file header",     self.add_header, "")

        separator(parent).pack(fill="x", padx=16, pady=(10, 0))

        tk.Label(parent, text="MESH INFO", bg=C["panel"],
                 fg=C["text_dim"], font=("Segoe UI Semibold", 8)).pack(
                     anchor="w", padx=16, pady=(10, 2))
        separator(parent).pack(fill="x", padx=16)

        self._info_frame = tk.Frame(parent, bg=C["panel"])
        self._info_frame.pack(fill="x", padx=16, pady=4)
        self._info_labels = {}
        for key in ["Triangles", "Vertices", "Size X", "Size Y", "Size Z", "File KB"]:
            row = tk.Frame(self._info_frame, bg=C["panel"])
            row.pack(fill="x", pady=1)
            make_label(row, key, dim=True).pack(side="left")
            lbl = make_label(row, "-")
            lbl.pack(side="right")
            self._info_labels[key] = lbl

        separator(parent).pack(fill="x", padx=16, pady=(10, 0))

        btn_frame = tk.Frame(parent, bg=C["panel"])
        btn_frame.pack(fill="x", padx=16, pady=14)

        btn_row = tk.Frame(btn_frame, bg=C["panel"])
        btn_row.pack(fill="x")

        self._btn_load = make_button(btn_row, "⬆ Load STL", self._load_stl)
        self._btn_load.pack(side="left", fill="x", expand=True, padx=(0, 4))

        self._btn_convert = make_button(btn_row, "⚙ Convert to SCAD",
                                        self._do_convert, accent=True)
        self._btn_convert.pack(side="left", fill="x", expand=True, padx=(4, 0))
        self._btn_convert.config(state="disabled")

        self._progress = ttk.Progressbar(parent, mode="determinate",
                                         style="Horizontal.TProgressbar")
        self._progress.pack(fill="x", padx=16, pady=(6, 0))

    def _build_right(self, parent):
        nb = ttk.Notebook(parent)
        nb.pack(fill="both", expand=True, padx=6, pady=6)
        self._notebook = nb

        self._tab_preview = tk.Frame(nb, bg=C["bg"])
        nb.add(self._tab_preview, text="  3D Preview  ")
        self._build_preview_tab(self._tab_preview)

        self._tab_scad = tk.Frame(nb, bg=C["bg"])
        nb.add(self._tab_scad, text="  SCAD Output  ")
        self._build_scad_tab(self._tab_scad)

        self._tab_log = tk.Frame(nb, bg=C["bg"])
        nb.add(self._tab_log, text="  Log  ")
        self._build_log_tab(self._tab_log)

    def _build_preview_tab(self, parent):
        if not HAS_MPL:
            tk.Label(parent,
                     text="matplotlib not installed.\nRun: pip install matplotlib",
                     bg=C["bg"], fg=C["error"], font=FONT_MONO).pack(expand=True)
            return

        toolbar_row = tk.Frame(parent, bg=C["panel"])
        toolbar_row.pack(fill="x")
        make_label(toolbar_row, "  Drag to rotate  |  Scroll to zoom",
                   dim=True).pack(side="left", padx=8, pady=4)
        make_button(toolbar_row, "Reset View",
                    self._reset_view).pack(side="right", padx=8, pady=4)
        make_button(toolbar_row, "Solid",
                    lambda: self._set_style("solid")).pack(side="right", padx=(0, 4), pady=4)
        make_button(toolbar_row, "Wire",
                    lambda: self._set_style("wire")).pack(side="right", padx=(0, 4), pady=4)

        separator(parent).pack(fill="x")

        self._fig = plt.Figure(figsize=(6, 5), facecolor=C["bg"])
        self._ax  = self._fig.add_subplot(111, projection="3d", facecolor=C["bg"])
        self._style_axes()

        self._canvas = FigureCanvasTkAgg(self._fig, master=parent)
        self._canvas.get_tk_widget().pack(fill="both", expand=True)

        self._canvas.mpl_connect("button_press_event",   self._on_mouse_press)
        self._canvas.mpl_connect("button_release_event", self._on_mouse_release)
        self._canvas.mpl_connect("motion_notify_event",  self._on_mouse_drag)
        self._canvas.mpl_connect("scroll_event",         self._on_scroll)

        self._empty_preview()

    def _style_axes(self):
        ax = self._ax
        ax.set_facecolor(C["bg"])
        for pane in [ax.xaxis.pane, ax.yaxis.pane, ax.zaxis.pane]:
            pane.fill = False
            pane.set_edgecolor(C["border"])
        ax.tick_params(colors=C["text_dim"], labelsize=7)
        ax.xaxis.label.set_color(C["text_dim"])
        ax.yaxis.label.set_color(C["text_dim"])
        ax.zaxis.label.set_color(C["text_dim"])
        for spine in ax.spines.values():
            spine.set_color(C["border"])

    def _empty_preview(self):
        if not HAS_MPL:
            return
        self._ax.cla()
        self._style_axes()
        self._ax.text(0, 0, 0, "Load an STL file\nto preview",
                      ha="center", va="center",
                      color=C["text_dim"], fontsize=11)
        self._canvas.draw_idle()

    def _build_scad_tab(self, parent):
        toolbar = tk.Frame(parent, bg=C["panel"])
        toolbar.pack(fill="x")
        make_button(toolbar, "📋 Copy All", self._copy_scad).pack(side="left", padx=8, pady=4)
        make_button(toolbar, "💾 Save",     self._save_scad).pack(side="left", padx=(0, 8), pady=4)
        self._scad_line_lbl = make_label(toolbar, "", dim=True)
        self._scad_line_lbl.pack(side="right", padx=8, pady=4)
        separator(parent).pack(fill="x")

        self._scad_text = scrolledtext.ScrolledText(
            parent,
            bg=C["entry_bg"], fg=C["text_dim"],
            insertbackground=C["text"],
            selectbackground=C["accent"],
            selectforeground=C["bg"],
            relief="flat", bd=0,
            font=FONT_MONO,
            wrap="none",
        )
        self._scad_text.pack(fill="both", expand=True)
        self._scad_text.insert("1.0", "// Load an STL file and click Convert to SCAD to see output here.")
        self._scad_text.config(state="disabled")

    def _build_log_tab(self, parent):
        self._log = scrolledtext.ScrolledText(
            parent,
            bg=C["entry_bg"], fg=C["text_dim"],
            insertbackground=C["text"],
            relief="flat", bd=0,
            font=FONT_MONO,
            wrap="word",
            state="disabled",
        )
        self._log.pack(fill="both", expand=True)
        self._log.tag_config("ok",    foreground=C["accent2"])
        self._log.tag_config("warn",  foreground=C["warn"])
        self._log.tag_config("error", foreground=C["error"])
        self._log.tag_config("info",  foreground=C["accent"])

    def _build_statusbar(self):
        bar = tk.Frame(self, bg=C["bg"], pady=4)
        bar.pack(fill="x", padx=12)
        self._status = tk.Label(bar, text="Ready - load an STL file to begin.",
                                bg=C["bg"], fg=C["text_dim"], font=FONT_LABEL)
        self._status.pack(side="left")

    def _log_msg(self, msg, tag=""):
        ts = time.strftime("%H:%M:%S")
        self._log.config(state="normal")
        self._log.insert("end", f"[{ts}]  {msg}\n", tag)
        self._log.see("end")
        self._log.config(state="disabled")

    def _set_status(self, msg, color=None):
        self._status.config(text=msg, fg=color or C["text_dim"])

    def _browse_input(self):
        path = filedialog.askopenfilename(
            title="Open STL File",
            filetypes=[("STL Files", "*.stl *.STL"), ("All Files", "*.*")])
        if not path:
            return
        self.input_path.set(path)
        if not self.output_path.get():
            self.output_path.set(os.path.splitext(path)[0] + ".scad")
        if not self.module_name.get() or self.module_name.get() == "shape":
            name = os.path.splitext(os.path.basename(path))[0]
            name = name.replace(" ", "_").replace("-", "_")
            self.module_name.set(name)

    def _browse_output(self):
        path = filedialog.asksaveasfilename(
            title="Save SCAD File",
            defaultextension=".scad",
            filetypes=[("OpenSCAD Files", "*.scad"), ("All Files", "*.*")])
        if path:
            self.output_path.set(path)

    def _load_stl(self):
        path = self.input_path.get().strip()
        if not path:
            messagebox.showwarning("No File", "Please select an STL input file first.")
            return
        if not os.path.isfile(path):
            messagebox.showerror("Not Found", f"File not found:\n{path}")
            return

        self._btn_load.config(state="disabled")
        self._btn_convert.config(state="disabled")
        self._set_status("Loading STL...", C["warn"])
        self._log_msg(f"Loading: {path}", "info")

        def _do():
            try:
                m, uv, faces, stats = load_stl(path)
                self.after(0, lambda: self._on_loaded(m, uv, faces, stats))
            except Exception as ex:
                self.after(0, lambda e=ex: self._on_load_error(e))

        threading.Thread(target=_do, daemon=True).start()

    def _on_loaded(self, m, uv, faces, stats):
        self._mesh_obj     = m
        self._unique_verts = uv
        self._faces        = faces
        self._stats        = stats

        sz = stats["size"]
        updates = {
            "Triangles": f"{stats['triangles']:,}",
            "Vertices":  f"{stats['unique_verts']:,}",
            "Size X":    f"{sz['x']:.3f}",
            "Size Y":    f"{sz['y']:.3f}",
            "Size Z":    f"{sz['z']:.3f}",
            "File KB":   f"{stats['file_size_kb']:.1f}",
        }
        for k, v in updates.items():
            self._info_labels[k].config(text=v)

        self._btn_load.config(state="normal")
        self._btn_convert.config(state="normal")
        self._set_status(
            f"Loaded - {stats['triangles']:,} triangles, {stats['unique_verts']:,} vertices",
            C["accent2"])
        self._log_msg(
            f"OK  triangles={stats['triangles']:,}  verts={stats['unique_verts']:,}", "ok")

        self._render_preview()

    def _on_load_error(self, ex):
        self._btn_load.config(state="normal")
        self._set_status(f"Load failed: {ex}", C["error"])
        self._log_msg(f"ERROR: {ex}", "error")
        messagebox.showerror("Load Error", str(ex))

    def _render_preview(self):
        if not HAS_MPL or self._unique_verts is None:
            return

        self._ax.cla()
        self._style_axes()

        faces = self._faces
        MAX_PREVIEW_FACES = 5000
        sampled = False
        if len(faces) > MAX_PREVIEW_FACES:
            idx = np.random.choice(len(faces), MAX_PREVIEW_FACES, replace=False)
            faces = faces[idx]
            sampled = True

        tris = self._unique_verts[faces]

        if self._preview_mesh_style == "solid":
            poly = Poly3DCollection(tris, alpha=0.85,
                                    facecolor="#1e3a5f", edgecolor="#2d5a8e",
                                    linewidth=0.1)
        else:
            poly = Poly3DCollection(tris, alpha=0.0,
                                    edgecolor=C["accent"], linewidth=0.3)

        self._ax.add_collection3d(poly)

        all_pts = self._unique_verts.flatten()
        self._ax.auto_scale_xyz(all_pts, all_pts, all_pts)
        self._ax.view_init(elev=self._preview_angle[0], azim=self._preview_angle[1])

        if sampled:
            self._ax.set_title(
                f"Preview: {MAX_PREVIEW_FACES:,} of {len(self._faces):,} faces",
                color=C["text_dim"], fontsize=8, pad=4)

        self._canvas.draw_idle()

    def _set_style(self, style):
        self._preview_mesh_style = style
        self._render_preview()

    def _reset_view(self):
        self._preview_angle = [30, -45]
        self._render_preview()

    def _on_mouse_press(self, event):
        if event.button == 1:
            self._drag_start = (event.x, event.y, *self._preview_angle)

    def _on_mouse_release(self, event):
        self._drag_start = None

    def _on_mouse_drag(self, event):
        if self._drag_start is None:
            return
        dx = event.x - self._drag_start[0]
        dy = event.y - self._drag_start[1]
        self._preview_angle[0] = self._drag_start[2] - dy * 0.5
        self._preview_angle[1] = self._drag_start[3] + dx * 0.5
        if self._unique_verts is not None:
            now = time.time()
            if now - self._last_drag_draw < 0.03:
                return
            self._last_drag_draw = now
            self._ax.view_init(elev=self._preview_angle[0], azim=self._preview_angle[1])
            self._canvas.draw_idle()

    def _on_scroll(self, event):
        if self._unique_verts is None:
            return
        factor = 0.9 if event.button == "up" else 1.1
        xlim = self._ax.get_xlim3d()
        ylim = self._ax.get_ylim3d()
        zlim = self._ax.get_zlim3d()
        cx = sum(xlim) / 2
        cy = sum(ylim) / 2
        cz = sum(zlim) / 2
        rx = (xlim[1] - xlim[0]) / 2
        ry = (ylim[1] - ylim[0]) / 2
        rz = (zlim[1] - zlim[0]) / 2
        self._ax.set_xlim3d([cx - rx * factor, cx + rx * factor])
        self._ax.set_ylim3d([cy - ry * factor, cy + ry * factor])
        self._ax.set_zlim3d([cz - rz * factor, cz + rz * factor])
        self._canvas.draw_idle()

    def _do_convert(self):
        if self._unique_verts is None:
            messagebox.showwarning("Not Loaded", "Load an STL file first.")
            return

        try:
            scale = float(self.scale_str.get())
        except ValueError:
            messagebox.showerror("Invalid Scale", "Scale must be a number (e.g. 1.0).")
            return

        out = self.output_path.get().strip()
        if not out:
            out = filedialog.asksaveasfilename(
                title="Save SCAD File",
                defaultextension=".scad",
                filetypes=[("OpenSCAD Files", "*.scad"), ("All Files", "*.*")])
            if not out:
                return
            self.output_path.set(out)

        self._btn_convert.config(state="disabled")
        self._btn_load.config(state="disabled")
        self._progress["value"] = 0
        self._set_status("Converting...", C["warn"])
        self._log_msg("Starting conversion...", "info")

        params = dict(
            unique_verts = self._unique_verts,
            faces        = self._faces,
            stats        = self._stats,
            module_name  = self.module_name.get().strip() or "shape",
            precision    = self.precision.get(),
            convexity    = self.convexity.get(),
            scale_factor = scale,
            center       = self.center.get(),
            add_call     = self.add_call.get(),
            add_header   = self.add_header.get(),
            winding_flip = self.winding.get(),
        )
        out_path = out

        def _progress(v):
            self.after(0, lambda: self._progress.configure(value=v))

        def _do():
            try:
                t0   = time.time()
                scad = convert_to_scad(**params, progress_cb=_progress)
                with open(out_path, "w", encoding="utf-8") as fh:
                    fh.write(scad)
                elapsed = time.time() - t0
                self.after(0, lambda: self._on_convert_done(scad, out_path, elapsed))
            except Exception as ex:
                self.after(0, lambda e=ex: self._on_convert_error(e))

        threading.Thread(target=_do, daemon=True).start()

    def _on_convert_done(self, scad: str, path: str, elapsed: float):
        lines   = scad.count("\n") + 1
        size_kb = len(scad.encode()) / 1024

        self._scad_text.config(state="normal")
        self._scad_text.delete("1.0", "end")
        self._scad_text.insert("1.0", scad)
        self._scad_text.config(state="disabled")
        self._scad_line_lbl.config(text=f"{lines:,} lines  |  {size_kb:.1f} KB")

        self._btn_convert.config(state="normal")
        self._btn_load.config(state="normal")
        self._progress["value"] = 100

        self._set_status(
            f"Done in {elapsed:.2f}s  ->  {path}  ({size_kb:.1f} KB)", C["accent2"])
        self._log_msg(
            f"Saved: {path}  [{lines:,} lines, {size_kb:.1f} KB, {elapsed:.2f}s]", "ok")

        self._notebook.select(1)

    def _on_convert_error(self, ex):
        self._btn_convert.config(state="normal")
        self._btn_load.config(state="normal")
        self._set_status(f"Conversion failed: {ex}", C["error"])
        self._log_msg(f"ERROR: {ex}", "error")
        messagebox.showerror("Conversion Error", str(ex))

    def _copy_scad(self):
        content = self._scad_text.get("1.0", "end")
        self.clipboard_clear()
        self.clipboard_append(content)
        self._set_status("Copied to clipboard.", C["accent"])

    def _save_scad(self):
        out = self.output_path.get().strip()
        if not out:
            out = filedialog.asksaveasfilename(
                defaultextension=".scad",
                filetypes=[("OpenSCAD Files", "*.scad")])
        if not out:
            return
        content = self._scad_text.get("1.0", "end")
        with open(out, "w", encoding="utf-8") as fh:
            fh.write(content)
        self._log_msg(f"Saved: {out}", "ok")
        self._set_status(f"Saved: {out}", C["accent2"])


if __name__ == "__main__":
    app = ScadifyApp()
    app.mainloop()
